$id: http://valohai.com/base.json
type: array
items:
  type: object
  properties:
    step:
      "$ref": "./step.json"
    endpoint:
      "$ref": "./endpoint.json"
    pipeline:
      "$ref": "./pipeline.json"
    task:
      "$ref": "./task.json"
